/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DemoRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'organization' : IDL.Text,
});
export const Time = IDL.Int;
export const IdentificationRecord = IDL.Record({
  'status' : IDL.Text,
  'dentalPatternHash' : IDL.Text,
  'matchScore' : IDL.Nat,
  'subjectId' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addIdentificationRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
  'getAllIdentificationRecords' : IDL.Func(
      [],
      [IDL.Vec(IdentificationRecord)],
      ['query'],
    ),
  'submitDemoRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DemoRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'organization' : IDL.Text,
  });
  const Time = IDL.Int;
  const IdentificationRecord = IDL.Record({
    'status' : IDL.Text,
    'dentalPatternHash' : IDL.Text,
    'matchScore' : IDL.Nat,
    'subjectId' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addIdentificationRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
    'getAllIdentificationRecords' : IDL.Func(
        [],
        [IDL.Vec(IdentificationRecord)],
        ['query'],
      ),
    'submitDemoRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };